<?php

namespace Tests\Feature\User;

use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use App\User;

class ProfileTest extends TestCase
{
    use DatabaseMigrations;

    private $user;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = factory(User::class)->create();
    }

    /** @test */
    public function guest_cannot_see_profile_page()
    {
        $this->get(route('my-profile'))
            ->assertRedirect('login');
    }

    /** @test */
    public function an_user_can_see_profile_details()
    {
        $this->actingAs($this->user)
            ->get(route('my-profile'))
            ->assertSeeText($this->user->email)
            ->assertSeeText($this->user->name);
    }

    /** @test */
/*    public function name_field_is_required_on_profile_page_form()
    {
        $this->actingAs($this->user)
            ->post(route('profile-save'), [])
            ->assertSessionHasErrors(['name']);
    }*/

    /** @test */
    public function an_user_cannot_edit_email_on_profile_page_form()
    {
    }
}
