<?php

namespace Tests\Feature\Event;

use App\User;
use App\Models\Event;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class EventTest extends TestCase
{

    use DatabaseMigrations;

    private $user;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = factory(User::class)->create();
    }

    public function a_guest_should_not_see_events_list()
    {
        $this->get(route('events'))
            ->assertRedirect(route('login'));
    }

    // the method name should start at 'test'
    public function testUserCanSeeListOfEvents()
    {
        $event = factory(Event::class)->create();

        // vendor/bin/phpunit
        $this->actingAs($this->user)
            ->get(route('events'))
            ->assertStatus(200);
/*            ->assertSeeText($event->title)
            ->assertSeeText($event->description);*/
    }

    public function a_guest_can_see_event_detail()
    {
        $event = factory(Event::class)->create();

        $this->actingAs($this->user)
            ->get(route('event-view'), $event->slug)
            ->assertSeeText($event->title)
            -assertSeeText($event->creator->name);
    }

}
