<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Event extends Model
{
    protected $guarded = [];

    protected $fillable = [
        'title',
        'description',
        'address',
        'lat',
        'lng',
        'start_date',
        'end_date',
        'user_id',
        'slug'
    ];
    // overright parent method
    public function getRouteKeyName()
    {
        return 'slug';// 通过slug而不是id作为route的索引
//        return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}
